### ISSUE TITLE
Access to the list of websites that activate auto reader view

### ISSUE THREAD

**Issue by Vasileski88** [pmarchwiak/auto-reader-view#7]
So I recently switched to librewolf from firefox and I'd like to keep using auto reader view. But the problem is don't know how to transfer the list of websites that activate auto reader view to the new browser. Is there a way and what is it?
Thanks.

**Comment by pmarchwiak** [comment]
The extension does not currently have a way to export or import the list of websites. 

I'm only speculating here but maybe there's a way to use Firefox developer tools to get access to the simple-storage APIs while pointing at your profile where the data is stored. This is the API that gets used: https://github.com/pmarchwiak/auto-reader-view/blob/1.0.2/auto-reader-view/index.js#L5
The domains are stored in the array `storage.domains` as you can see here: https://github.com/pmarchwiak/auto-reader-view/blob/1.0.2/auto-reader-view/index.js#L149-L155

**Comment by yllekz** [comment]
Yeah this extension sorely needs the ability to import/export lists of sites in bulk. I use a competing firefox extension called "[Automatic Reader View](https://addons.mozilla.org/en-US/firefox/addon/automatic-reader-view/)" which allows one to paste in a comma-separated list of sites. 

I love that this extension has a UI button for enabling/disabling auto reader mode on the fly compared to Automatic Reader View but yet this extension lacks the bulk import/export options, so neither extension is the winner here.

**Comment by pmarchwiak** [comment]
@yllekz I released version 1.0.3 of the extension and it now has this feature. You'll be able to view and edit the saved domains in bulk - visit the Preferences page for the extension (from the Firefox menu button, Add-ons and Themes, then select Extensions, then auto-reader-view, then Preferences). I'd love to hear if you have any feedback!

Navigating to the extension preferences is a little difficult so I'm thinking I'll add a quick link to that page from the pop up panel in a future release.
